#!/usr/bin/env php
<?php

##################################################
# Config
##################################################

define('ERRORS', true);
define('PACKAGED', false);

# Path to pcon console_abstract.php
define('CONSOLE_ABSTRACT_PATH', __DIR__ . '/src/console_abstract.php');

# Paths to other includes
$src_includes = array(
    __DIR__ . '/src/pcon.php',
);

##################################################

require_once CONSOLE_ABSTRACT_PATH;

# vim: syntax=php
