#!/usr/bin/env php
<?php
##################################################
# Config
##################################################
define('ERRORS', false);
define('PACKAGED', true);

// Note: leave this for packaging ?>
