#!/usr/bin/env php
<?php
/**
 * @internal
 */
##################################################
# Config
##################################################
if (!defined('ERRORS')) define('ERRORS', false);
if (!defined('PACKAGED')) define('PACKAGED', true);

// Note: leave this for packaging ?>
