#!/usr/bin/env php
<?php

##################################################
# Config
##################################################

if (!defined('ERRORS')) define('ERRORS', true);
if (!defined('PACKAGED')) define('PACKAGED', false);

# Path to pcon console_abstract.php
if (!defined('CONSOLE_ABSTRACT_PATH')) define('CONSOLE_ABSTRACT_PATH', '{{console_abstract_path}}');

# Paths to other includes
$src_includes = array(
    __DIR__ . DIRECTORY_SEPARATOR . 'src' . DIRECTORY_SEPARATOR . '{{tool_shortname}}.php',
);

##################################################

if (empty($_PACKAGING)) // defined when loading file to do packaging
{
    require_once CONSOLE_ABSTRACT_PATH;
}

# vim: syntax=php
